version: "3"

services:
  frontend:
    image: dejavxtrem/frontend
    ports:
      - 80:80
  reverseproxy: 
    image: dejavxtrem/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend
      - frontend
   
  backend:
    image: dejavxtrem/backend
    ports:
      - 5050:5050
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1