# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1


orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0
  docker: circleci/docker@2.0.1


commands:
  destroy-cluster:
    description: Destroy EKS Cluster.
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string

    steps:
      - run:
          name: Destroy Environments
          command: |
             aws cloudformation delete-stack --stack-name eksctl-<< parameters.cluster-name >>-cluster --region us-east-2

jobs:
  lintcheck:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.3-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/backend

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pwd
            ls -l
            cd backend
            python3 -m venv ~/.capstone
            . ~/.capstone/bin/activate
            make install
      - save_cache:
          paths:
            - .~/.capstone/backend
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run lint
          command: |
            pwd
            ls -l
            cd backend
            . ~/.capstone/bin/activate
            make lint


workflows:
  deployments:
    jobs:
      - lintcheck