# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1


orbs:
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.4.0
  docker: circleci/docker@2.0.1


commands:
  destroy-cluster:
    description: Destroy EKS Cluster.
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string

    steps:
      - run:
          name: Destroy Environments
          command: |
             aws cloudformation delete-stack --stack-name eksctl-<< parameters.cluster-name >>-cluster --region us-east-2

jobs:
  lintcheck:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: python:3.7.3-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.capstone
            source  ~/.capstone/bin/activate
            ls -l
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - .~/.capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run lint
          command: |
            pwd
            source  ~/.capstone/bin/activate
            ls -l
            make lint

  build-Docker-Push-frontend:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build frontend Image
          command: |
            # build frontend image and tag it.
            cd frontend
            docker build -t dejavxtrem/frontend .
            docker tag dejavxtrem/frontend dejavxtrem/frontend:latest
      - run:
          name: push frontend image to Docker hub
          command: |
            docker image ls
            docker login -u $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker push dejavxtrem/frontend:latest

workflows:
  deployments:
    jobs:
      - lintcheck
      - build-Docker-Push-frontend:
          requires:
            - lintcheck