apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        service: backend
        api: external        
    spec:
      containers:
      - image: dejavxtrem/backend
        name: backend
        imagePullPolicy: Always          
        ports:
        - containerPort: 5050
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: FLASK_ENV   
          value: "development"
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_DEBUG
          value: "1"

      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
spec:
  ports:
  - name: "5050"
    port: 5050
    targetPort: 5050
  selector:
    service: backend